services:
  # --- SeaweedFS master ---
  master:
    image: chrislusf/seaweedfs:4.31
    user: seaweed
    container_name: seaweed-master
    command: >
      master
      -ip=master
      -port=9333
      -mdir=/data
      -peers=none
      -defaultReplication=000
      -volumeSizeLimitMB=1024
    ports:
      - "9333:9333"
    volumes:
      - ./data/master:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9333/cluster/status"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: on-failure:5
    networks:
      - ngelmak-net

  # --- Filer: Write Access ---
  filer:
    image: chrislusf/seaweedfs:4.31
    user: seaweed
    container_name: seaweed-filer
    # Key Flags:
    # -defaultReplicaPlacement=000 : No replication (for testing, not recommended for production)
    command: >
      filer
      -master=master:9333
      -ip=filer
      -port=9555
      -defaultReplicaPlacement=000
    depends_on:
      - master
      - volume1
    ports:
      - "9555:9555" # Only expose to internal network or localhost
    volumes:
      - ./data/filer_meta:/data/filer_meta
      - ./data/config/filer.toml:/etc/seaweedfs/filer.toml:ro
    restart: on-failure:5
    networks:
      - ngelmak-net

  # --- PUBLIC: For Consumers (Read Only Access) ---
  filer-ro:
    image: chrislusf/seaweedfs:4.31
    user: seaweed
    container_name: seaweed-filer-read
    # Key Flags:
    # -port.readonly 8888 : Public port (Read ONLY, ignores writes)
    # -disableDirListing=true : Allows directory listing (can be a security risk, set to true in production)
    # -exposeDirectoryData=false : Hides folder contents (lists return empty)
    # -ui.deleteDir=false : Disables delete option in UI (for safety)
    command: >
      filer
      -master=master:9333
      -ip=filer-ro
      -port=9555
      -port.readonly=8888
      -disableDirListing=true
      -exposeDirectoryData=false
      -ui.deleteDir=false
    depends_on:
      - master
      - volume1
      - filer
    ports:
      - "8888:8888" # For Public (Read Only Access)
    volumes:
      - ./data/config/filer.toml:/etc/seaweedfs/filer.toml:ro
    restart: on-failure:5
    networks:
      - ngelmak-net

  # --- Volume servers (can be spread across nodes) ---
  volume1:
    image: chrislusf/seaweedfs:4.31
    user: seaweed
    container_name: seaweed-volume1
    command: >
      volume
      -master=master:9333
      -ip=volume1
      -ip.bind=volume1
      -port=8080
      -dir=/data
      -max=2
    depends_on:
      master:
        condition: service_healthy
    ports:
      - "8081:8080"
    volumes:
      - ./data/volume1:/data
    restart: on-failure:5
    networks:
      - ngelmak-net

networks:
  ngelmak-net:
    external: true